version: '3.1'

services:
  db:
    image: mysql:5.7
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_PASSWORD: aviator_password 
      MYSQL_DATABASE: aviator_db
      MYSQL_USER: aviator_dev
    ports:
      - "3306:3306"
    volumes:
      - ./aviator.sql:/docker-entrypoint-initdb.d/aviator.sql
